apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: quinoa-wind-turbine
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: quinoa-wind-turbine
    app.kubernetes.io/part-of: quinoa-wind-turbine
  name: quinoa-wind-turbine
spec:
  replicas: 5
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: quinoa-wind-turbine
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: quinoa-wind-turbine
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/kdubois1-tenant/quinoa-wind-turbine/quinoa-wind-turbine@sha256:947e6d0a5fa5527ce22f355b55a1a11943b08b420ecda6bd5baf21570eb4461a
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 80
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
